slice_name: Anzahl Elemente mit Problem
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 44__table
  viz_type: echarts_timeseries_bar
  slice_id: 159
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 4
  matrixify_cell_title_template: ''
  x_axis: Baustelle
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Elemente mit Problem
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 886
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: REAL
      type_generic: 0
      uuid: eed10a90-9d4e-4c29-9836-638d2024383c
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(Elemente mit Problem)
    optionName: metric_xyd8s1qklv_nt2ovyhomb
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: Monat
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastEnabled: false
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: ''
  x_axis_title_margin: 0
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  sort_series_ascending: false
  color_scheme: supersetColors
  show_value: true
  color_by_primary_axis: false
  minorTicks: false
  zoomable: false
  show_legend: false
  x_axis_time_format: smart_date
  x_axis_number_format: ~g
  xAxisLabelRotation: 45
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: false
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  echart_options: ''
  extra_form_data: {}
  dashboards:
  - 33
query_context: '{"datasource":{"id":44,"type":"table"},"force":false,"queries":[{"filters":[{"col":"Monat","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"Baustelle","label":"Baustelle","expressionType":"SQL","isColumnReference":true}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Elemente
  mit Problem","description":null,"expression":"","filterable":true,"groupby":true,"id":886,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"uuid":"eed10a90-9d4e-4c29-9836-638d2024383c","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(Elemente
  mit Problem)","optionName":"metric_xyd8s1qklv_nt2ovyhomb","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Elemente
  mit Problem","description":null,"expression":"","filterable":true,"groupby":true,"id":886,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"uuid":"eed10a90-9d4e-4c29-9836-638d2024383c","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(Elemente
  mit Problem)","optionName":"metric_xyd8s1qklv_nt2ovyhomb","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["Baustelle"],"columns":[],"aggregates":{"SUM(Elemente
  mit Problem)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"44__table","viz_type":"echarts_timeseries_bar","slice_id":159,"matrixify_enable":false,"matrixify_mode_columns":"disabled","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_all_sort_by_columns":"a_to_z","matrixify_topn_order_columns":true,"matrixify_show_column_headers":true,"matrixify_fit_columns_dynamically":true,"matrixify_mode_rows":"disabled","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_all_sort_by_rows":"a_to_z","matrixify_topn_order_rows":true,"matrixify_show_row_labels":true,"matrixify_row_height":300,"matrixify_charts_per_row":4,"matrixify_cell_title_template":"","x_axis":"Baustelle","metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Elemente
  mit Problem","description":null,"expression":"","filterable":true,"groupby":true,"id":886,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"REAL","type_generic":0,"uuid":"eed10a90-9d4e-4c29-9836-638d2024383c","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(Elemente
  mit Problem)","optionName":"metric_xyd8s1qklv_nt2ovyhomb","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"Monat"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastEnabled":false,"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title":"","x_axis_title_margin":0,"y_axis_title":"","y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","sort_series_ascending":false,"color_scheme":"supersetColors","show_value":true,"color_by_primary_axis":false,"minorTicks":false,"zoomable":false,"show_legend":false,"x_axis_time_format":"smart_date","x_axis_number_format":"~g","xAxisLabelRotation":45,"xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","logAxis":false,"minorSplitLine":false,"truncateYAxis":false,"y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":false,"tooltipSortByMetric":false,"tooltipTimeFormat":"smart_date","echart_options":"","extra_form_data":{},"dashboards":[33],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 303644fc-7a25-47c3-a98f-69cd49c9aaa9
version: 1.0.0
dataset_uuid: 16205e47-97ee-42c3-a324-722ba4b899f3
