slice_name: '% Defekt 2026'
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 44__table
  viz_type: big_number_total
  slice_id: 158
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 4
  matrixify_cell_title_template: ''
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: SUM("Elemente mit Problem") * 1.0 / SUM("Anzahl Elemente")
    optionName: metric_o2o6ersc8l_zhknod1pr3
    sqlExpression: SUM("Elemente mit Problem") * 1.0 / SUM("Anzahl Elemente")
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: Monat LIKE '2026%'
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_83ydn2d8yxx_q9o4qt82rv9
  header_font_size: 0.4
  subtitle_font_size: 0.15
  show_metric_name: false
  metric_name_font_size: 0.15
  y_axis_format: ',.1%'
  time_format: smart_date
  force_timestamp_formatting: false
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 33
query_context: '{"datasource":{"id":44,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":"(Monat
  LIKE ''2026%'')"},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"SUM(\"Elemente
  mit Problem\") * 1.0 / SUM(\"Anzahl Elemente\")","optionName":"metric_o2o6ersc8l_zhknod1pr3","sqlExpression":"SUM(\"Elemente
  mit Problem\") * 1.0 / SUM(\"Anzahl Elemente\")"}],"annotation_layers":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"44__table","viz_type":"big_number_total","slice_id":158,"matrixify_enable":false,"matrixify_mode_columns":"disabled","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_all_sort_by_columns":"a_to_z","matrixify_topn_order_columns":true,"matrixify_show_column_headers":true,"matrixify_fit_columns_dynamically":true,"matrixify_mode_rows":"disabled","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_all_sort_by_rows":"a_to_z","matrixify_topn_order_rows":true,"matrixify_show_row_labels":true,"matrixify_row_height":300,"matrixify_charts_per_row":4,"matrixify_cell_title_template":"","metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"SUM(\"Elemente
  mit Problem\") * 1.0 / SUM(\"Anzahl Elemente\")","optionName":"metric_o2o6ersc8l_zhknod1pr3","sqlExpression":"SUM(\"Elemente
  mit Problem\") * 1.0 / SUM(\"Anzahl Elemente\")"},"adhoc_filters":[{"expressionType":"SQL","sqlExpression":"Monat
  LIKE ''2026%''","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_83ydn2d8yxx_q9o4qt82rv9"}],"header_font_size":0.4,"subtitle_font_size":0.15,"show_metric_name":false,"metric_name_font_size":0.15,"y_axis_format":",.1%","time_format":"smart_date","force_timestamp_formatting":false,"conditional_formatting":[],"extra_form_data":{},"dashboards":[33],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 2a1624f3-ed6c-4508-9733-ca57e7d92769
version: 1.0.0
dataset_uuid: 16205e47-97ee-42c3-a324-722ba4b899f3
